language: node_js
addons:
  ssh_known_hosts: 58.87.87.24
node_js:
- node
cache: npm
branches:
only:
- dev
before_install:
- openssl aes-256-cbc -K $encrypted_b22c92291d53_key -iv $encrypted_b22c92291d53_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 666 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- npm install -g hexo-cli
install:
- git submodule update --init --recursive
- npm install
before_script:
- git config --global user.name $USER_NAME
- git config --global user.email $USER_EMAIL
script:
- pwd
- hexo clean
- hexo generate
- hexo algolia
after_success:
- hexo deploy
- ll ~/.ssh/
- cat ~/.ssh/id_rsa
- whoami
