hemes/next/dist: xenial
language: node_js
addons:
  ssh_known_hosts: $UBUNTU
node_js:
  - node
  - 10.15.0
cache: npm
branches:
only:
  - dev
before_install:
  - openssl aes-256-cbc -K $encrypted_b22c92291d53_key -iv $encrypted_b22c92291d53_iv
<<<<<<< HEAD
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
=======
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
>>>>>>> master
  - eval "$(ssh-agent -s)"
  - chmod 600 /.ssh/id_rsa
  - ssh-add /.ssh/id_rsa
  - npm install -g hexo-cli
install:
  - git submodule update --init --recursive
  - npm install
before_script:
  - git config --global user.name $USER_NAME
  - git config --global user.email $USER_EMAIL
script:
  - pwd
  - hexo clean
  - hexo generate
  - hexo algolia
after_success:
  - hexo deploy
